//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public string Uname { get; set; }
        public string pass { get; set; }
        public string @class { get; set; }
        public int id { get; set; }
    }
}
